#ifndef ADAS_PERCEPTION_BOUNDINGBOX_HPP
#define ADAS_PERCEPTION_BOUNDINGBOX_HPP

// This file was generated by the ScoreGen C++ template for data type descriptions

#include <cstdint>

#include <array>
#include <chrono>
#include <list>
#include <vector>


namespace adas {
namespace perception {

struct BoundingBox {
    float x_min { 0 };
    float y_min { 0 };
    float x_max { 0 };
    float y_max { 0 };
};

}  // namespace perception
}  // namespace adas

#endif  // ADAS_PERCEPTION_BOUNDINGBOX_HPP
