#ifndef ADAS_PERCEPTION_BRAKECOMMAND_HPP
#define ADAS_PERCEPTION_BRAKECOMMAND_HPP

// This file was generated by the ScoreGen C++ template for data type descriptions

#include <cstdint>

#include <array>
#include <chrono>
#include <list>
#include <vector>

#include <adas/perception/BrakeSource.hpp>

namespace adas {
namespace perception {

struct BrakeCommand {
    std::chrono::time_point timestamp {  };
    float brake_pressure_bar { 0 };
    bool emergency_brake { false };
    float target_deceleration_mps2 { 0 };
    float ttc_seconds { 999 };
    adas::perception::BrakeSource command_source {  };
};

}  // namespace perception
}  // namespace adas

#endif  // ADAS_PERCEPTION_BRAKECOMMAND_HPP
