#ifndef ADAS_PERCEPTION_BRAKESOURCE_HPP
#define ADAS_PERCEPTION_BRAKESOURCE_HPP

// This file was generated by the ScoreGen C++ template for enum data type descriptions

#include <cstdint>

#include <string>

namespace adas {
namespace perception {

enum class BrakeSource  : uint8_t  {
    kManual  = 0,
    kAEB  = 1,
    kACC  = 2,
    kCollisionAvoidance  = 3,
};

}  // namespace perception
}  // namespace adas

template <>
[[nodiscard]] inline std::optional<const char*> std::to_string(const adas::perception::BrakeSource enumerator) noexcept {
    switch (enumerator) {
        case adas::perception::BrakeSource::kManual:
            return "adas::perception::BrakeSource::kManual";
        case adas::perception::BrakeSource::kAEB:
            return "adas::perception::BrakeSource::kAEB";
        case adas::perception::BrakeSource::kACC:
            return "adas::perception::BrakeSource::kACC";
        case adas::perception::BrakeSource::kCollisionAvoidance:
            return "adas::perception::BrakeSource::kCollisionAvoidance";
        default:
            return NullOpt;
    }
}

#endif  // ADAS_PERCEPTION_BRAKESOURCE_HPP
