#ifndef ADAS_PERCEPTION_CAMERAFRAME_HPP
#define ADAS_PERCEPTION_CAMERAFRAME_HPP

// This file was generated by the ScoreGen C++ template for data type descriptions

#include <cstdint>

#include <array>
#include <chrono>
#include <list>
#include <vector>


namespace adas {
namespace perception {

struct CameraFrame {
    std::chrono::time_point timestamp {  };
    uint64_t sequence_id { 0 };
    uint32_t width { 1920 };
    uint32_t height { 1080 };
    std::array<uint8_t, 6220800> image_data {  };
    uint8_t camera_id { 0 };
    uint32_t exposure_time_us { 33333 };
};

}  // namespace perception
}  // namespace adas

#endif  // ADAS_PERCEPTION_CAMERAFRAME_HPP
