// This file was generated by the ScoreGen C++ template for constexpr type descriptions

#ifndef ADAS_PERCEPTION_CONSTEXPRS_HPP
#define ADAS_PERCEPTION_CONSTEXPRS_HPP

#include <array>
#include <chrono>
#include <list>
#include <vector>
#include <cstdint>



namespace adas {
namespace perception {

constexpr float MaxDetectionDistance { 150 };
constexpr float EmergencyBrakeThreshold { 2.5 };
constexpr uint32_t CameraFrameRate { 30 };
constexpr float MaxTrafficSignDetectionRange { 100 };
constexpr float TrafficSignConfidenceThreshold { 0.8 };

}  // namespace perception
}  // namespace adas

#endif  // ADAS_PERCEPTION_CONSTEXPRS_HPP
