#ifndef ADAS_PERCEPTION_DETECTEDTRAFFICSIGN_HPP
#define ADAS_PERCEPTION_DETECTEDTRAFFICSIGN_HPP

// This file was generated by the ScoreGen C++ template for data type descriptions

#include <cstdint>

#include <array>
#include <chrono>
#include <list>
#include <vector>

#include <adas/perception/TrafficSignType.hpp>
#include <adas/perception/BoundingBox.hpp>

namespace adas {
namespace perception {

struct DetectedTrafficSign {
    adas::perception::TrafficSignType sign_type {  };
    float confidence { 0 };
    adas::perception::BoundingBox bounding_box {  };
    float distance_m { 0 };
    uint8_t speed_limit_value { 0 };
    uint32_t sign_id { 0 };
};

}  // namespace perception
}  // namespace adas

#endif  // ADAS_PERCEPTION_DETECTEDTRAFFICSIGN_HPP
