#ifndef ADAS_PERCEPTION_DETECTEDOBJECT_HPP
#define ADAS_PERCEPTION_DETECTEDOBJECT_HPP

// This file was generated by the ScoreGen C++ template for data type descriptions

#include <cstdint>

#include <array>
#include <chrono>
#include <list>
#include <vector>

#include <adas/perception/ObjectClass.hpp>
#include <adas/perception/BoundingBox.hpp>

namespace adas {
namespace perception {

struct DetectedObject {
    adas::perception::ObjectClass object_class {  };
    float confidence { 0 };
    adas::perception::BoundingBox bounding_box {  };
    float distance_m { 0 };
    float velocity_mps { 0 };
};

}  // namespace perception
}  // namespace adas

#endif  // ADAS_PERCEPTION_DETECTEDOBJECT_HPP
