#ifndef ADAS_PERCEPTION_LOGENTRY_HPP
#define ADAS_PERCEPTION_LOGENTRY_HPP

// This file was generated by the ScoreGen C++ template for data type descriptions

#include <cstdint>

#include <array>
#include <chrono>
#include <list>
#include <vector>

#include <adas/perception/LogLevel.hpp>

namespace adas {
namespace perception {

struct LogEntry {
    std::chrono::time_point timestamp {  };
    adas::perception::LogLevel log_level {  };
    std::string component_name { "" };
    std::string message { "" };
    uint32_t thread_id { 0 };
};

}  // namespace perception
}  // namespace adas

#endif  // ADAS_PERCEPTION_LOGENTRY_HPP
