#ifndef ADAS_PERCEPTION_LOGLEVEL_HPP
#define ADAS_PERCEPTION_LOGLEVEL_HPP

// This file was generated by the ScoreGen C++ template for enum data type descriptions

#include <cstdint>

#include <string>

namespace adas {
namespace perception {

enum class LogLevel  : uint8_t  {
    kDebug  = 0,
    kInfo  = 1,
    kWarning  = 2,
    kError  = 3,
    kFatal  = 4,
};

}  // namespace perception
}  // namespace adas

template <>
[[nodiscard]] inline std::optional<const char*> std::to_string(const adas::perception::LogLevel enumerator) noexcept {
    switch (enumerator) {
        case adas::perception::LogLevel::kDebug:
            return "adas::perception::LogLevel::kDebug";
        case adas::perception::LogLevel::kInfo:
            return "adas::perception::LogLevel::kInfo";
        case adas::perception::LogLevel::kWarning:
            return "adas::perception::LogLevel::kWarning";
        case adas::perception::LogLevel::kError:
            return "adas::perception::LogLevel::kError";
        case adas::perception::LogLevel::kFatal:
            return "adas::perception::LogLevel::kFatal";
        default:
            return NullOpt;
    }
}

#endif  // ADAS_PERCEPTION_LOGLEVEL_HPP
