#ifndef ADAS_PERCEPTION_OBJECTCLASS_HPP
#define ADAS_PERCEPTION_OBJECTCLASS_HPP

// This file was generated by the ScoreGen C++ template for enum data type descriptions

#include <cstdint>

#include <string>

namespace adas {
namespace perception {

enum class ObjectClass  : uint8_t  {
    kUnknown  = 0,
    kVehicle  = 1,
    kPedestrian  = 2,
    kCyclist  = 3,
    kTrafficSign  = 4,
    kTrafficLight  = 5,
    kObstacle  = 6,
};

}  // namespace perception
}  // namespace adas

template <>
[[nodiscard]] inline std::optional<const char*> std::to_string(const adas::perception::ObjectClass enumerator) noexcept {
    switch (enumerator) {
        case adas::perception::ObjectClass::kUnknown:
            return "adas::perception::ObjectClass::kUnknown";
        case adas::perception::ObjectClass::kVehicle:
            return "adas::perception::ObjectClass::kVehicle";
        case adas::perception::ObjectClass::kPedestrian:
            return "adas::perception::ObjectClass::kPedestrian";
        case adas::perception::ObjectClass::kCyclist:
            return "adas::perception::ObjectClass::kCyclist";
        case adas::perception::ObjectClass::kTrafficSign:
            return "adas::perception::ObjectClass::kTrafficSign";
        case adas::perception::ObjectClass::kTrafficLight:
            return "adas::perception::ObjectClass::kTrafficLight";
        case adas::perception::ObjectClass::kObstacle:
            return "adas::perception::ObjectClass::kObstacle";
        default:
            return NullOpt;
    }
}

#endif  // ADAS_PERCEPTION_OBJECTCLASS_HPP
