#ifndef ADAS_PERCEPTION_OBJECTDETECTIONS_HPP
#define ADAS_PERCEPTION_OBJECTDETECTIONS_HPP

// This file was generated by the ScoreGen C++ template for data type descriptions

#include <cstdint>

#include <array>
#include <chrono>
#include <list>
#include <vector>

#include <adas/perception/DetectedObject.hpp>

namespace adas {
namespace perception {

struct ObjectDetections {
    std::chrono::time_point timestamp {  };
    uint64_t source_frame_id {  };
    uint16_t num_objects { 0 };
    std::array<adas::perception::DetectedObject, 32> objects {  };
    uint32_t inference_time_us { 0 };
    float confidence_threshold { 0.7 };
};

}  // namespace perception
}  // namespace adas

#endif  // ADAS_PERCEPTION_OBJECTDETECTIONS_HPP
