#ifndef ADAS_PERCEPTION_PERFORMANCETRACE_HPP
#define ADAS_PERCEPTION_PERFORMANCETRACE_HPP

// This file was generated by the ScoreGen C++ template for data type descriptions

#include <cstdint>

#include <array>
#include <chrono>
#include <list>
#include <vector>


namespace adas {
namespace perception {

struct PerformanceTrace {
    std::chrono::time_point timestamp {  };
    std::string component_name { "" };
    std::string operation_name { "" };
    uint64_t duration_us { 0 };
    float cpu_usage_percent { 0 };
    uint32_t memory_usage_mb { 0 };
    std::string trace_data { "" };
};

}  // namespace perception
}  // namespace adas

#endif  // ADAS_PERCEPTION_PERFORMANCETRACE_HPP
