#ifndef ADAS_PERCEPTION_TRAFFICSIGNTYPE_HPP
#define ADAS_PERCEPTION_TRAFFICSIGNTYPE_HPP

// This file was generated by the ScoreGen C++ template for enum data type descriptions

#include <cstdint>

#include <string>

namespace adas {
namespace perception {

enum class TrafficSignType  : uint8_t  {
    kUnknownSign  = 0,
    kSpeedLimit30  = 30,
    kSpeedLimit50  = 50,
    kSpeedLimit70  = 70,
    kSpeedLimit90  = 90,
    kSpeedLimit130  = 130,
    kSpeedLimitEnd  = 200,
    kStop  = 201,
    kYield  = 202,
    kNoEntry  = 203,
    kConstruction  = 204,
    kSchoolZone  = 205,
};

}  // namespace perception
}  // namespace adas

template <>
[[nodiscard]] inline std::optional<const char*> std::to_string(const adas::perception::TrafficSignType enumerator) noexcept {
    switch (enumerator) {
        case adas::perception::TrafficSignType::kUnknownSign:
            return "adas::perception::TrafficSignType::kUnknownSign";
        case adas::perception::TrafficSignType::kSpeedLimit30:
            return "adas::perception::TrafficSignType::kSpeedLimit30";
        case adas::perception::TrafficSignType::kSpeedLimit50:
            return "adas::perception::TrafficSignType::kSpeedLimit50";
        case adas::perception::TrafficSignType::kSpeedLimit70:
            return "adas::perception::TrafficSignType::kSpeedLimit70";
        case adas::perception::TrafficSignType::kSpeedLimit90:
            return "adas::perception::TrafficSignType::kSpeedLimit90";
        case adas::perception::TrafficSignType::kSpeedLimit130:
            return "adas::perception::TrafficSignType::kSpeedLimit130";
        case adas::perception::TrafficSignType::kSpeedLimitEnd:
            return "adas::perception::TrafficSignType::kSpeedLimitEnd";
        case adas::perception::TrafficSignType::kStop:
            return "adas::perception::TrafficSignType::kStop";
        case adas::perception::TrafficSignType::kYield:
            return "adas::perception::TrafficSignType::kYield";
        case adas::perception::TrafficSignType::kNoEntry:
            return "adas::perception::TrafficSignType::kNoEntry";
        case adas::perception::TrafficSignType::kConstruction:
            return "adas::perception::TrafficSignType::kConstruction";
        case adas::perception::TrafficSignType::kSchoolZone:
            return "adas::perception::TrafficSignType::kSchoolZone";
        default:
            return NullOpt;
    }
}

#endif  // ADAS_PERCEPTION_TRAFFICSIGNTYPE_HPP
