#ifndef ADAS_PERCEPTION_TRAFFICSIGNCOMMAND_HPP
#define ADAS_PERCEPTION_TRAFFICSIGNCOMMAND_HPP

// This file was generated by the ScoreGen C++ template for data type descriptions

#include <cstdint>

#include <array>
#include <chrono>
#include <list>
#include <vector>

#include <adas/perception/DetectedTrafficSign.hpp>

namespace adas {
namespace perception {

struct TrafficSignCommand {
    std::chrono::time_point timestamp {  };
    std::array<adas::perception::DetectedTrafficSign, 8> detected_signs {  };
    uint8_t num_detected_signs { 0 };
    uint8_t current_speed_limit_kmh { 50 };
    uint8_t advisory_speed_kmh { 0 };
    bool warning_active { false };
    uint32_t processing_time_us { 0 };
};

}  // namespace perception
}  // namespace adas

#endif  // ADAS_PERCEPTION_TRAFFICSIGNCOMMAND_HPP
