load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "middleware",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.hpp"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//base",
    ],
)

cc_test(
    name = "middleware_test",
    srcs = glob(["test/**/*.cpp"]),
    deps = [
        ":middleware",
        "@googletest//:gtest_main",
    ],
)
