load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "base",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.hpp"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "base_test",
    srcs = glob(["test/**/*.cpp"]),
    deps = [
        ":base",
        "@googletest//:gtest_main",
    ],
)
